##
# database
##

import os, sys
import sqlite3 as lite

from lib import utils

# database
class dataBase():
    def open(self):
        try:
            self.conn = lite.connect('db/dancade.db3')
        except lite.Error as e:
            utils.logging.error('DB: %s:' % e.args[0])
            sys.exit(1)
        return(self.conn)

    def startTransaction(self):
        self.cur = self.conn.cursor()

    def commit(self):
        self.conn.commit()

    def rollback(self):
        self.conn.rollback()

    def insert(self, sql, values):
        self.cur.execute(sql, values)
        return(self.cur.lastrowid)

    def close(self):
        self.conn.close()

    def createDb(self):
        conn = self.open()
        with conn:
            # create a library of games table
            utils.logging.info('DB: creating a game library table')
            cur_libname = conn.cursor()
            cur_libname.execute('''CREATE TABLE libraryname (
                                    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
                                    name TEXT
                                )''')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Not Related")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Recently Played")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Top Rated")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Arcade / Pinball")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Arcade / Pinball * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Ball & Paddle / Breakout")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Ball & Paddle / Breakout * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Ball & Paddle / Jump and Touch")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Ball & Paddle / Misc.")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Ball & Paddle / Pong")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Board Game / Backgammon")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Board Game / Bridge Machine")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Board Game / Cards")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Board Game / Checker Machine")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Board Game / Chess Machine")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Board Game / Dame Machine")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Calculator / Astrological Computer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Calculator / Chemical Calculations")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Calculator / Desktop Electronic Calculator")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Calculator / Electronic Organizer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Calculator / Math Game Learning")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Calculator / Pocket Calculator")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Calculator / Pocket Computer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Calculator / Talking Calculator")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Casino / Bingo")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Casino / BlackJack")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Casino / Cards")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Casino / Cards * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Casino / Dice")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Casino / Horse Racing")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Casino / Lottery")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Casino / Misc.")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Casino / Misc. * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Casino / Multi-Games")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Casino / Multiplay")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Casino / Racing")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Casino / Roulette")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Casino / Skill Game")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Casino / Unknown")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Casino / Video Slot")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Climbing / Building")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Climbing / Mountain - Wall")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Climbing / Tree - Plant")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Computer / Business - Terminal")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Computer / Cablenet Controller")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Computer / Child Computer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Computer / Construction Kit")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Computer / Development System")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Computer / Educational Game")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Computer / Graphic Terminal")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Computer / Graphics Workstation")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Computer / Home System")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Computer / Laptop - Notebook - Portable")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Computer / Microcomputer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Computer / Milling")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Computer / Misc.")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Computer / Pocket Computer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Computer / Pocket PC")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Computer / Portable Digital Teletype")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Computer / Programming Machine")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Computer / Protocol Analyzer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Computer / Punched Car")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Computer / Single Board")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Computer / TTL")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Computer / TeleText Terminal")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Computer / Training Board")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Computer / Video Production")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Computer / Word-processing Machine")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Computer / Workstation")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Computer / Workstation - Server")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Computer Graphic Workstation / Broadcast Television")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Digital Simulator / Aquarium")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Driving / 1st Person")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Driving / Ambulance Guide")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Driving / Boat")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Driving / Catch")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Driving / Demolition Derby")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Driving / FireTruck Guide")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Driving / Guide and Collect")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Driving / Guide and Shoot")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Driving / Landing")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Driving / Misc.")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Driving / Motorbike")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Driving / Motorbike (Motocross)")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Driving / Plane")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Driving / Race")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Driving / Race (chase view)")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Driving / Race (chase view) Bike")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Driving / Race 1st Person")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Driving / Race Bike")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Driving / Race Track")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Driving / Truck Guide")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Electromechanical / Basketball")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Electromechanical / Beat Up")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Electromechanical / Bingo")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Electromechanical / Bowling")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Electromechanical / Change Money")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Electromechanical / Coin-Operated Rocking Games")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Electromechanical / Crane Machine")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Electromechanical / Darts")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Electromechanical / Hockey")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Electromechanical / Misc.")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Electromechanical / Pinball")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Electromechanical / Reels")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Electromechanical / Shooter")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Electromechanical / Shooting")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Electromechanical / Skill")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Electromechanical / Utilities")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Fighter / 2.5D")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Fighter / 2D")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Fighter / 3D")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Fighter / Compilation")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Fighter / Driving Vertical")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Fighter / Field")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Fighter / Misc.")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Fighter / Multiplay")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Fighter / Versus")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Fighter / Versus * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Fighter / Versus Co-op")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Fighter / Vertical")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Game / Gambling")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Game Console / Fitness Game")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Game Console / Gambling")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Game Console / Home Videogame")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Game Console / Home Videogame Console Expansion")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Game Console / Multi-Games")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Barcode Scanner")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Child Computer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Console Cartridge")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / E-Book Reading")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Educational Game")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Electronic Game")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Handpuppet Toy")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Home Videogame Console")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Horoscope")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Action")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Baseball")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Basketball")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Board Game")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Bowling")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Boxe")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Casino")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Compilation")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Criket")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Dance")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Driving")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Fashion")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Fighting")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Fishing")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Fitness")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Football")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Golf")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Hunting")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Maze")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Mini-Golf")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Multi-Games")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Multi-Sport")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Music")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Painting")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Pinball")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Ping Pong")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Puzzle")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Quiz")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Reader")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Role Playing")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Shoot \'em Up")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Shooter")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Skateboard")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Snowboard")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Soccer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Sudoku")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / TV Show")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Tennis")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Trail")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Plug n\' Play TV Game / Wrestling")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Pocket Device - Pad - PDA")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Handheld / Pocket Electronic Game")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Maze / Ball Guide")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Maze / Blocks")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Maze / Change Surface")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Maze / Collect")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Maze / Collect & Put")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Maze / Collect * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Maze / Cross")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Maze / Defeat Enemies")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Maze / Digging")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Maze / Digging * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Maze / Driving")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Maze / Driving * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Maze / Escape")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Maze / Escape * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Maze / Fighter")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Maze / Integrate")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Maze / Ladders")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Maze / Misc.")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Maze / Move and Sort")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Maze / Outline")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Maze / Paint")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Maze / Run Jump")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Maze / Shooter Large")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Maze / Shooter Small")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Maze / Surround")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Medal Game / Action")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Medal Game / Adventure")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Medal Game / Aquarium")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Medal Game / Baseball")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Medal Game / Bingo")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Medal Game / Cards")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Medal Game / Casino")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Medal Game / Coin Pusher")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Medal Game / Compilation")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Medal Game / Dance")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Medal Game / Driving")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Medal Game / Horse Racing")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Medal Game / Misc.")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Medal Game / Pinball")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Medal Game / Powerboat Racing")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Medal Game / Sport")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Medal Game / Stone-Scissor-Paper")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Medal Game / Timing")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Medal Game / Versus")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Medical Equipment / ECG Unit")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Medical Equipment / Visual Field Screener")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Bank-teller Terminal")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Car Voice Alert")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Cash Counter")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Catch")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Clock")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Coin Pusher")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Credit Card Terminal")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / DVD Player")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / DVD Reader-Writer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Dartboard")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Device Programmer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Digital MultiMeter (DMM)")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Document Processors")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Dog Sitter")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Dot-Matrix Display")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Drum Machine")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / EPROM Programmer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Educational Game")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Electronic Board Game")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Electronic Game")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Electronic Typewriter")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Engine Control Unit")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Fingerprint Reader")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Gambling Board")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Graphic Tablet")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Graphics Display Controller")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Hot-air Balloon")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / In Circuit Emulator")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Jump and Bounce")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Laserdisc Player")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Laserdisc Simulator")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Mini-Games")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Multiplay")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Order")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Pachinko")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Portable Media Player")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Prediction")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Print Club")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Response Time")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Robot Control")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Satellite Receiver")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Shoot Photos")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Similar Bowling Game")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Spank * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Speech Synthesizer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Teletype")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Temperature Controller")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Time-Access Control Terminal")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Toy Cars")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Toy Robot")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Unknown")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / VTR Control")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Versus")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Virtual Environment")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Misc. / Wavetables Generator")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("MultiGame / Compilation")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("MultiGame / Compilation * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("MultiGame / Gambling")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("MultiGame / Gambling Board")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("MultiGame / Mini-Games")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Multiplay / Compilation")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Multiplay / Mini-Games")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Multiplay / Mini-Games * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Multiplay / Misc.")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Multiplay / Misc. * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Music / Audio Chip Emulator")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Music / Audio Sequencer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Music / Digital Piano")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Music / Drum Machine")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Music / Drum Machine Module")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Music / Electronic Piano")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Music / Guitar Effects")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Music / Guitar Synthesizer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Music / Guitar Synthesizer Module")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Music / Instruments")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Music / JukeBox")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Music / Karaoke Machine")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Music / Keyboard")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Music / MIDI Player")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Music / MIDI Sound Generator")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Music / Misc.")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Music / Player")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Music / Sampler Editor")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Music / Sequencer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Music / Sound Module")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Music / Storage Media")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Music / Synthesizer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Music / Synthesizer Module")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Music / Tone Generator")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Music / Vocoder - Harmonizer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Music / Workstation")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Music Game / Dance")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Music Game / Instruments")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Music Game / Misc.")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Platform / Fighter")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Platform / Fighter Scrolling")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Platform / Maze")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Platform / Run Jump")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Platform / Run Jump * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Platform / Run, Jump & Scrolling")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Platform / Shooter")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Platform / Shooter Scrolling")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Printer / 3D Printer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Printer / Barcode Printer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Printer / Handbook")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Printer / Laser Printer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Printer / Matrix Printer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Printer / Thermal Printer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Puzzle / Cards")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Puzzle / Drop")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Puzzle / Drop * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Puzzle / Match")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Puzzle / Match * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Puzzle / Maze")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Puzzle / Misc.")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Puzzle / Misc. * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Puzzle / Outline")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Puzzle / Outline * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Puzzle / Paint * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Puzzle / Reconstruction")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Puzzle / Reconstruction * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Puzzle / Sliding")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Puzzle / Sliding * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Puzzle / Toss")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Puzzle / Toss * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Quiz / Hangman game")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Quiz / Questions in Chinese")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Quiz / Questions in English")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Quiz / Questions in English * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Quiz / Questions in French")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Quiz / Questions in German")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Quiz / Questions in Greek")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Quiz / Questions in Italian")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Quiz / Questions in Japanese")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Quiz / Questions in Japanese * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Quiz / Questions in Korean")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Quiz / Questions in Norwegian")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Quiz / Questions in Spanish")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Redemption Game / Action")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Redemption Game / Crane Machine")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Redemption Game / Driving")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Redemption Game / Flying")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Redemption Game / Pinball")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Redemption Game / Reaction")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Redemption Game / Shooter")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Redemption Game / Soccer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / 1st Person")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / 2.5D")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / 3rd Person")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / Command")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / Driving")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / Driving (chase view)")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / Driving 1st Person")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / Driving Diagonal")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / Driving Horizontal")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / Driving Vertical")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / Field")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / Flying")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / Flying (chase view)")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / Flying * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / Flying 1st Person")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / Flying Diagonal")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / Flying Horizontal")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / Flying Horizontal * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / Flying Vertical")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / Flying Vertical * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / Gallery")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / Gallery * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / Gun")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / Misc.")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / Misc. Horizontal")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / Misc. Vertical")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / Motorbike")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / Outline * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / Submarine")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / Underwater")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / Versus")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Shooter / Walking")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Simulation / Pet Management Simulation")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Slot Machine / Reels")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Slot Machine / Video Slot")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Slot Machine / Video Slot * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Armwrestling")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Baseball")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Basketball")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Bowling")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Boxing")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Bull Fighting")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Cards")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Darts")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Dodgeball")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Fishing")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Football")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Golf")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Gun")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Handball")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Hang Gliding")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Hockey")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Horse Racing")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Horseshoes")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Misc.")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Multiplay")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Ping Pong")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Pool")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Pool * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Roller")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Rugby Football")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Shuffleboard")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Skateboarding")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Skiing")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / SkyDiving")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Soccer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Sumo")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Swimming")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Tennis")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Track & Field")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Volley - Soccer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Volleyball")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Sports / Wrestling")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("System / BIOS")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("System / Device")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("TTL * Ball & Paddle / Breakout")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("TTL * Ball & Paddle / Pong")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("TTL * Driving / Demolition Derby")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("TTL * Driving / Motorbike")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("TTL * Driving / Race")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("TTL * Driving / Race Track")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("TTL * Maze / Shooter Small")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("TTL * Quiz / Questions in English")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("TTL * Shooter / Field")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("TTL * Shooter / Flying 1st Person")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("TTL * Shooter / Flying Vertical")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("TTL * Shooter / Gallery")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("TTL * Shooter / Gun")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("TTL * Shooter / Misc. Vertical")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("TTL * Shooter / Underwater")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("TTL * Shooter / Versus")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("TTL * Sports / Baseball")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("TTL * Sports / Horse Racing")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Tablet / Multi-Functional for Children")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Tabletop / Cards")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Tabletop / Go")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Tabletop / Hanafuda")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Tabletop / Hanafuda * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Tabletop / Mahjong")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Tabletop / Mahjong * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Tabletop / Match * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Tabletop / Misc.")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Tabletop / Multi-Games")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Tabletop / Multiplay")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Tabletop / Othello - Reversi")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Tabletop / Othello - Reversi * Mature *")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Tabletop / Renju")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Tabletop / Shougi")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Telephone / Car Phone")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Telephone / ComputerPhone")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Telephone / Landline Phone")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Telephone / Landline phone")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Telephone / Mobile Phone - Smartphone")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Touchscreen / Multi-Games")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / Analog Filter Module")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / Arcade Switcher")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / Arcade System")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / Clock")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / Devices Communication")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / Disk Unit")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / EPROM Programmer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / Electronic Digital Thermostat")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / Light Gun")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / Modem")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / Monitor")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / Network Controller")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / Network Processor")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / On-board BUS Ticketing")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / PAL Demo")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / Redemption Board")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / Robot Control")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / Speech Synthesizer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / TV Test Pattern Generator")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / Test")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / Test ROM")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / Thermometer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / Tobacco Vending Machine")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / Update")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / Video Switcher")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / Videocassette Player/Recorder")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / Videosynthesizer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / Wave Synthesizer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / Weather Forecast Machine")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / Weather Station")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Utilities / Weight Scale")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Watch / LCD Game")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Whac-A-Mole / Fighter")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Whac-A-Mole / Footsteps")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Whac-A-Mole / Gun")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Whac-A-Mole / Hammer")')
            cur_libname.execute('INSERT INTO libraryname (name) VALUES ("Whac-A-Mole / Shooter")')

            cur_libgame = conn.cursor()
            cur_libgame.execute('''CREATE TABLE library (
                                    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
                                    idgame INTEGER,
                                    idlibname INTEGER,
                                    FOREIGN KEY(idgame) REFERENCES game(id),
                                    FOREIGN KEY(idlibname) REFERENCES libraryname(id)
                                )''')
            # Create a games list table
            utils.logging.info('DB: creating a game list table')
            cur_game = conn.cursor()
            cur_game.execute('''CREATE TABLE game ( \
                                id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
                                game TEXT,
                                description TEXT,
                                year TEXT,
                                manufacturer TEXT,
                                picture TEXT,
                                video TEXT,
                                lastplayed TEXT,
                                playcount INTEGER,
                                rating INTEGER,
                                status INTEGER
                            )''')
            conn.commit()
        self.close()

    def queryLibrary(self):
        # Generate a library
        library_list = []
        conn = self.open()
        cur_lib = conn.cursor()
        cur_lib.execute("SELECT * FROM libraryname")
        data_lib = cur_lib.fetchall()
        
        cur_lib2 = conn.cursor()
        for line in data_lib:
            cur_lib2.execute("SELECT COUNT(*) FROM library WHERE library.idlibname = %d" % line[0])
            data_lib2 = cur_lib2.fetchone()
            if data_lib2[0] > 0 and not 'BIOS' in line[1]:
                library_list.append(line)

        conn.close()
        return(library_list)

    def queryGame(self):
        # Generate a games list
        utils.logging.info('DB: generating a simple list of games')
        conn = self.open()
        cur_game = conn.cursor()
        cur_game.execute("SELECT * FROM game ORDER BY 'description'")
        data_game = cur_game.fetchall()
        cur_game.execute("SELECT COUNT(*) FROM game")
        data_game_count = cur_game.fetchone()
        conn.close()
        return(data_game, data_game_count)

    def queryOrganicGames(self, library, order_by='libraryname.name'):
        # Generate a games list
        conn = self.open()
        cur_game = conn.cursor()
        cur_game.execute('''SELECT game.id, game.game, game.description, game.year, game.manufacturer,
                                game.picture, game.video, game.lastplayed, game.playcount,
                                game.rating, game.status, libraryname.name
                            FROM game
                                INNER JOIN library
                                    ON game.id = library.idgame
                                INNER JOIN libraryname
                                    ON library.idlibname = libraryname.id
                            WHERE library.idlibname = %s
                            ORDER BY %s''' % (library, order_by))

        data_game = cur_game.fetchall()
        conn.close()
        return(data_game)

# checks
def check_db_exist():
    if not os.path.isfile('db/dancade.db3'):
        utils.logging.info('DB: dancade needs to update the game database from mame')
        return(False)
    else:
        db = dataBase()
        data_game, game_count = db.queryGame()
        utils.logging.info('DB: game counted: %d' % game_count)
        if game_count[0] > 0:
            utils.logging.info('DB: database dancade exists.')
            return(True)
        else:
            utils.logging.info('DB: dancade needs to update the game database from mame')
            return(False)

def check_library(library):
    # check if a library exists
    db = dataBase()
    conn = db.open()
    cur_lib = conn.cursor()
    cur_lib.execute("SELECT * FROM libraryname WHERE name = '%s'" % library)
    data_lib = cur_lib.fetchone()
    conn.close()
    if data_lib == None:
        return(False)
    else:
        return(data_lib)
